commvault: cancelBackup execution
gomorpheus/morpheus-commvault-plugin pull request #16
Opened 2024-07-23 11:11 UTC by rahulray19

2024-07-23 13:00 UTC, ddeyoung requested changes

2024-07-23 13:00 UTC, ddeyoung commented on src/main/groovy/com/morpheusdata/commvault/CommvaultBackupExecutionProvider.groovy
> +		authConfig.token = authConfig.token ?: CommvaultBackupUtility.getToken(authConfig.apiUrl, authConfig.username, authConfig.password)?.token
This method should not fetch a token. If `authConfig` has a token, then logout. If `authConfig` doesn't have a token then we have no session to logout.

2024-07-23 14:12 UTC, rahulray19 commented on src/main/groovy/com/morpheusdata/commvault/CommvaultBackupExecutionProvider.groovy
> +		authConfig.token = authConfig.token ?: CommvaultBackupUtility.getToken(authConfig.apiUrl, authConfig.username, authConfig.password)?.token
changes made as suggested

2024-07-25 12:31 UTC, ddeyoung approved these changes

2024-07-25 12:31 UTC, merged