morpheus-50 client dataset
gomorpheus/morpheus-commvault-plugin pull request #2
Opened 2024-06-19 11:19 UTC by rahulray19

2024-06-24 12:35 UTC, ddeyoung requested changes

2024-06-24 12:35 UTC, ddeyoung commented on src/main/groovy/com/morpheusdata/commvault/datasets/CommvaultClientsDatasetProvider.groovy
> +        return null
This should return `ReferenceData.class`

2024-06-24 12:42 UTC, rahulray19 commented on src/main/groovy/com/morpheusdata/commvault/datasets/CommvaultClientsDatasetProvider.groovy
> +        return null
change added as suggested

2024-06-25 12:39 UTC, ddeyoung approved these changes

2024-06-25 12:39 UTC, merged